# https://dukemon.leetserve.com/posts/2020/01/banzai-kafka-in-kubernetes/
---
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: kafka
spec:
  clusterRef:
    name: kafka
  name: test-topic
  partitions: 1
  replicationFactor: 3
  config:
    "retention.ms": "604800000"
    "cleanup.policy": "delete"
